var annotated_dup =
[
    [ "alexandria", "namespacealexandria.xhtml", [
      [ "anonymous_namespace{interactionEnergyTest.cpp}", "namespacealexandria_1_1anonymous__namespace_02interactionEnergyTest_8cpp_03.xhtml", [
        [ "InteractionEnergyTest", "classalexandria_1_1anonymous__namespace_02interactionEnergyTest_8cpp_03_1_1InteractionEnergyTest.xhtml", "classalexandria_1_1anonymous__namespace_02interactionEnergyTest_8cpp_03_1_1InteractionEnergyTest" ]
      ] ],
      [ "anonymous_namespace{qgen_acmTest.cpp}", "namespacealexandria_1_1anonymous__namespace_02qgen__acmTest_8cpp_03.xhtml", [
        [ "AcmTest", "classalexandria_1_1anonymous__namespace_02qgen__acmTest_8cpp_03_1_1AcmTest.xhtml", "classalexandria_1_1anonymous__namespace_02qgen__acmTest_8cpp_03_1_1AcmTest" ]
      ] ],
      [ "anonymous_namespace{qgen_respTest.cpp}", "namespacealexandria_1_1anonymous__namespace_02qgen__respTest_8cpp_03.xhtml", [
        [ "RespTest", "classalexandria_1_1anonymous__namespace_02qgen__respTest_8cpp_03_1_1RespTest.xhtml", "classalexandria_1_1anonymous__namespace_02qgen__respTest_8cpp_03_1_1RespTest" ]
      ] ],
      [ "anonymous_namespace{qtypeTest.cpp}", "namespacealexandria_1_1anonymous__namespace_02qtypeTest_8cpp_03.xhtml", [
        [ "QtypeTest", "classalexandria_1_1anonymous__namespace_02qtypeTest_8cpp_03_1_1QtypeTest.xhtml", "classalexandria_1_1anonymous__namespace_02qtypeTest_8cpp_03_1_1QtypeTest" ]
      ] ],
      [ "ACMFitnessComputer", "classalexandria_1_1ACMFitnessComputer.xhtml", "classalexandria_1_1ACMFitnessComputer" ],
      [ "ACMIndividual", "classalexandria_1_1ACMIndividual.xhtml", "classalexandria_1_1ACMIndividual" ],
      [ "ACMInitializer", "classalexandria_1_1ACMInitializer.xhtml", "classalexandria_1_1ACMInitializer" ],
      [ "ACTEnergy", "classalexandria_1_1ACTEnergy.xhtml", "classalexandria_1_1ACTEnergy" ],
      [ "ACTHelper", "classalexandria_1_1ACTHelper.xhtml", "classalexandria_1_1ACTHelper" ],
      [ "ACTMiddleMan", "classalexandria_1_1ACTMiddleMan.xhtml", "classalexandria_1_1ACTMiddleMan" ],
      [ "ACTMol", "classalexandria_1_1ACTMol.xhtml", "classalexandria_1_1ACTMol" ],
      [ "ACTQprop", "classalexandria_1_1ACTQprop.xhtml", "classalexandria_1_1ACTQprop" ],
      [ "AllBondeds", "classalexandria_1_1AllBondeds.xhtml", "classalexandria_1_1AllBondeds" ],
      [ "Angle", "classalexandria_1_1Angle.xhtml", "classalexandria_1_1Angle" ],
      [ "AtomNum", "classalexandria_1_1AtomNum.xhtml", "classalexandria_1_1AtomNum" ],
      [ "AtomPair", "classalexandria_1_1AtomPair.xhtml", "classalexandria_1_1AtomPair" ],
      [ "B2Data", "classalexandria_1_1B2Data.xhtml", "classalexandria_1_1B2Data" ],
      [ "BayesConfigHandler", "classalexandria_1_1BayesConfigHandler.xhtml", "classalexandria_1_1BayesConfigHandler" ],
      [ "Bond", "classalexandria_1_1Bond.xhtml", "classalexandria_1_1Bond" ],
      [ "BoundsDevComputer", "classalexandria_1_1BoundsDevComputer.xhtml", "classalexandria_1_1BoundsDevComputer" ],
      [ "CalcAtom", "classalexandria_1_1CalcAtom.xhtml", "classalexandria_1_1CalcAtom" ],
      [ "CategoryList", "classalexandria_1_1CategoryList.xhtml", "classalexandria_1_1CategoryList" ],
      [ "Classes", "classalexandria_1_1Classes.xhtml", "classalexandria_1_1Classes" ],
      [ "CompoundReader", "classalexandria_1_1CompoundReader.xhtml", "classalexandria_1_1CompoundReader" ],
      [ "ConfigHandler", "classalexandria_1_1ConfigHandler.xhtml", "classalexandria_1_1ConfigHandler" ],
      [ "DevComputer", "classalexandria_1_1DevComputer.xhtml", "classalexandria_1_1DevComputer" ],
      [ "ElectrostaticPotential", "classalexandria_1_1ElectrostaticPotential.xhtml", "classalexandria_1_1ElectrostaticPotential" ],
      [ "EspDevComputer", "classalexandria_1_1EspDevComputer.xhtml", "classalexandria_1_1EspDevComputer" ],
      [ "EspPoint", "classalexandria_1_1EspPoint.xhtml", "classalexandria_1_1EspPoint" ],
      [ "Experiment", "classalexandria_1_1Experiment.xhtml", "classalexandria_1_1Experiment" ],
      [ "FittingTarget", "classalexandria_1_1FittingTarget.xhtml", "classalexandria_1_1FittingTarget" ],
      [ "ForceComputer", "classalexandria_1_1ForceComputer.xhtml", "classalexandria_1_1ForceComputer" ],
      [ "ForceEnergyDevComputer", "classalexandria_1_1ForceEnergyDevComputer.xhtml", "classalexandria_1_1ForceEnergyDevComputer" ],
      [ "ForceFieldParameter", "classalexandria_1_1ForceFieldParameter.xhtml", "classalexandria_1_1ForceFieldParameter" ],
      [ "ForceFieldParameterList", "classalexandria_1_1ForceFieldParameterList.xhtml", "classalexandria_1_1ForceFieldParameterList" ],
      [ "Fragment", "classalexandria_1_1Fragment.xhtml", "classalexandria_1_1Fragment" ],
      [ "FragmentHandler", "classalexandria_1_1FragmentHandler.xhtml", "classalexandria_1_1FragmentHandler" ],
      [ "GAConfigHandler", "classalexandria_1_1GAConfigHandler.xhtml", "classalexandria_1_1GAConfigHandler" ],
      [ "GenericProperty", "classalexandria_1_1GenericProperty.xhtml", "classalexandria_1_1GenericProperty" ],
      [ "Harmonics", "classalexandria_1_1Harmonics.xhtml", "classalexandria_1_1Harmonics" ],
      [ "HarmonicsDevComputer", "classalexandria_1_1HarmonicsDevComputer.xhtml", "classalexandria_1_1HarmonicsDevComputer" ],
      [ "Identifier", "classalexandria_1_1Identifier.xhtml", "classalexandria_1_1Identifier" ],
      [ "Improper", "classalexandria_1_1Improper.xhtml", "classalexandria_1_1Improper" ],
      [ "JsonTree", "classalexandria_1_1JsonTree.xhtml", "classalexandria_1_1JsonTree" ],
      [ "LongTable", "classalexandria_1_1LongTable.xhtml", "classalexandria_1_1LongTable" ],
      [ "MCMCMutator", "classalexandria_1_1MCMCMutator.xhtml", "classalexandria_1_1MCMCMutator" ],
      [ "MolecularComposition", "classalexandria_1_1MolecularComposition.xhtml", "classalexandria_1_1MolecularComposition" ],
      [ "MolecularEnergy", "classalexandria_1_1MolecularEnergy.xhtml", "classalexandria_1_1MolecularEnergy" ],
      [ "MolecularMultipole", "classalexandria_1_1MolecularMultipole.xhtml", "classalexandria_1_1MolecularMultipole" ],
      [ "MolecularPolarizability", "classalexandria_1_1MolecularPolarizability.xhtml", "classalexandria_1_1MolecularPolarizability" ],
      [ "MolGen", "classalexandria_1_1MolGen.xhtml", "classalexandria_1_1MolGen" ],
      [ "MolHandler", "classalexandria_1_1MolHandler.xhtml", "classalexandria_1_1MolHandler" ],
      [ "MolProp", "classalexandria_1_1MolProp.xhtml", "classalexandria_1_1MolProp" ],
      [ "MsgHandler", "classalexandria_1_1MsgHandler.xhtml", "classalexandria_1_1MsgHandler" ],
      [ "MultiPoleDevComputer", "classalexandria_1_1MultiPoleDevComputer.xhtml", "classalexandria_1_1MultiPoleDevComputer" ],
      [ "OneBonded", "classalexandria_1_1OneBonded.xhtml", "classalexandria_1_1OneBonded" ],
      [ "OpenMMWriter", "classalexandria_1_1OpenMMWriter.xhtml", "classalexandria_1_1OpenMMWriter" ],
      [ "OptACM", "classalexandria_1_1OptACM.xhtml", "classalexandria_1_1OptACM" ],
      [ "OptimizationIndex", "classalexandria_1_1OptimizationIndex.xhtml", "classalexandria_1_1OptimizationIndex" ],
      [ "ParamCombRule", "classalexandria_1_1ParamCombRule.xhtml", "classalexandria_1_1ParamCombRule" ],
      [ "ParticleType", "classalexandria_1_1ParticleType.xhtml", "classalexandria_1_1ParticleType" ],
      [ "PercentMutator", "classalexandria_1_1PercentMutator.xhtml", "classalexandria_1_1PercentMutator" ],
      [ "PolarDevComputer", "classalexandria_1_1PolarDevComputer.xhtml", "classalexandria_1_1PolarDevComputer" ],
      [ "PotentialProperties", "structalexandria_1_1PotentialProperties.xhtml", "structalexandria_1_1PotentialProperties" ],
      [ "Proper", "classalexandria_1_1Proper.xhtml", "classalexandria_1_1Proper" ],
      [ "QgenAcm", "classalexandria_1_1QgenAcm.xhtml", "classalexandria_1_1QgenAcm" ],
      [ "QtypeProps", "classalexandria_1_1QtypeProps.xhtml", "classalexandria_1_1QtypeProps" ],
      [ "RefCount", "classalexandria_1_1RefCount.xhtml", "classalexandria_1_1RefCount" ],
      [ "SingleAtom", "classalexandria_1_1SingleAtom.xhtml", "classalexandria_1_1SingleAtom" ],
      [ "StaticIndividualInfo", "classalexandria_1_1StaticIndividualInfo.xhtml", "classalexandria_1_1StaticIndividualInfo" ],
      [ "StlbfgsHandler", "classalexandria_1_1StlbfgsHandler.xhtml", "classalexandria_1_1StlbfgsHandler" ],
      [ "Synonym", "classalexandria_1_1Synonym.xhtml", "classalexandria_1_1Synonym" ],
      [ "TopologyEntry", "classalexandria_1_1TopologyEntry.xhtml", "classalexandria_1_1TopologyEntry" ],
      [ "TrainForceFieldPrinter", "classalexandria_1_1TrainForceFieldPrinter.xhtml", "classalexandria_1_1TrainForceFieldPrinter" ],
      [ "Vsite1", "classalexandria_1_1Vsite1.xhtml", "classalexandria_1_1Vsite1" ],
      [ "Vsite2", "classalexandria_1_1Vsite2.xhtml", "classalexandria_1_1Vsite2" ],
      [ "Vsite3", "classalexandria_1_1Vsite3.xhtml", "classalexandria_1_1Vsite3" ],
      [ "Vsite4", "classalexandria_1_1Vsite4.xhtml", "classalexandria_1_1Vsite4" ],
      [ "VsiteHandler", "classalexandria_1_1VsiteHandler.xhtml", "classalexandria_1_1VsiteHandler" ]
    ] ],
    [ "anonymous_namespace{atomizationenergyTest.cpp}", "namespaceanonymous__namespace_02atomizationenergyTest_8cpp_03.xhtml", [
      [ "AtomizationEnergyTest", "classanonymous__namespace_02atomizationenergyTest_8cpp_03_1_1AtomizationEnergyTest.xhtml", "classanonymous__namespace_02atomizationenergyTest_8cpp_03_1_1AtomizationEnergyTest" ]
    ] ],
    [ "ga", "namespacega.xhtml", [
      [ "BoltzmannProbabilityComputer", "classga_1_1BoltzmannProbabilityComputer.xhtml", "classga_1_1BoltzmannProbabilityComputer" ],
      [ "CatastrophePenalizer", "classga_1_1CatastrophePenalizer.xhtml", "classga_1_1CatastrophePenalizer" ],
      [ "Crossover", "classga_1_1Crossover.xhtml", "classga_1_1Crossover" ],
      [ "EmptySorter", "classga_1_1EmptySorter.xhtml", "classga_1_1EmptySorter" ],
      [ "FitnessComputer", "classga_1_1FitnessComputer.xhtml", "classga_1_1FitnessComputer" ],
      [ "FitnessProbabilityComputer", "classga_1_1FitnessProbabilityComputer.xhtml", "classga_1_1FitnessProbabilityComputer" ],
      [ "GenePool", "classga_1_1GenePool.xhtml", "classga_1_1GenePool" ],
      [ "GenerationTerminator", "classga_1_1GenerationTerminator.xhtml", "classga_1_1GenerationTerminator" ],
      [ "GeneticAlgorithm", "classga_1_1GeneticAlgorithm.xhtml", "classga_1_1GeneticAlgorithm" ],
      [ "Individual", "classga_1_1Individual.xhtml", "classga_1_1Individual" ],
      [ "Initializer", "classga_1_1Initializer.xhtml", "classga_1_1Initializer" ],
      [ "Mutator", "classga_1_1Mutator.xhtml", "classga_1_1Mutator" ],
      [ "NPointCrossover", "classga_1_1NPointCrossover.xhtml", "classga_1_1NPointCrossover" ],
      [ "Penalizer", "classga_1_1Penalizer.xhtml", "classga_1_1Penalizer" ],
      [ "ProbabilityComputer", "classga_1_1ProbabilityComputer.xhtml", "classga_1_1ProbabilityComputer" ],
      [ "QuickSorter", "classga_1_1QuickSorter.xhtml", "classga_1_1QuickSorter" ],
      [ "RankProbabilityComputer", "classga_1_1RankProbabilityComputer.xhtml", "classga_1_1RankProbabilityComputer" ],
      [ "RouletteSelector", "classga_1_1RouletteSelector.xhtml", "classga_1_1RouletteSelector" ],
      [ "Selector", "classga_1_1Selector.xhtml", "classga_1_1Selector" ],
      [ "Sorter", "classga_1_1Sorter.xhtml", "classga_1_1Sorter" ],
      [ "Terminator", "classga_1_1Terminator.xhtml", "classga_1_1Terminator" ],
      [ "TestGenTerminator", "classga_1_1TestGenTerminator.xhtml", "classga_1_1TestGenTerminator" ],
      [ "VolumeFractionPenalizer", "classga_1_1VolumeFractionPenalizer.xhtml", "classga_1_1VolumeFractionPenalizer" ]
    ] ],
    [ "MatrixWrapper", "classMatrixWrapper.xhtml", "classMatrixWrapper" ],
    [ "RegressionTest", "classRegressionTest.xhtml", "classRegressionTest" ]
];